server:
  port: 8761

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
    prefer-ip-address: true